services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=user_service'
      - 'MYSQL_PASSWORD=etudiant'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=etudiant'
    ports:
      - 3309:3306 # permet de faire le port forwarding entre le port 3306 du conteneur et le port 3306 de la machine hôte
